import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {CurrentWeatherProvider} from "@/context/CurrentWeatherContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <CurrentWeatherProvider>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-sky-400 via-blue-300 to-blue-100 bg-no-repeat bg-cover min-h-screen`}
            >
            {children}
            </body>
        </CurrentWeatherProvider>
        </html>
    );
}
